theme_name = "Blogbuster"

labels = [
    "content",
    "field_2"
]


# Static assets to include/copy
#   `from` paths are relative to "src" dir
#   `to` paths are relative to "out" dir
[[include]]
desc = "Vendor JS file"
from = "../opt/bootstrap-5.1.3/dist/js/bootstrap.bundle.js"
to = "js"
[[include]]
desc = "Vendor JS file map"
from = "../opt/bootstrap-5.1.3/dist/js/bootstrap.bundle.js"
to = "js"

[[include]]
desc = "JS files"
from = "js/"
to = "js"

[[include]]
desc = "CSS files"
from = "css/"
to = "css"


# Sample text for preview of the layout
[preview.post]
content = '''
    #some/tags
    <h1>Title</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum rem eaque, saepe illum soluta corporis? Ducimus iste quis et similique amet eum aut maxime nulla! Exercitationem facilis atque veritatis quos.
    Suscipit aperiam asperiores eum reprehenderit quis repudiandae esse dolorum animi earum odio illo libero quas fuga iusto ullam facilis commodi labore, magni aliquid reiciendis eaque sint error officiis. Vero, aliquam!</p>
    <p>Bu da demektir ki gev, gev, gev, gev. <code>≈ü√∂yle</code>, <code>b√∂yle</code>. Hele hele lorem, perferendis quas vel esse deleniti rem, illo veritatis. Corrupti consectetur ex delectus, suscipit explicabo error quasi, laudantium sapiente modi ea tenetur alias. Praesentium est soluta illo id quaerat unde iure enim quisquam amet. Cumque saepe quos aliquid quod ratione sapiente officiis voluptatum esse reprehenderit!</p>
    <h3>Sub heading</h3>
    <p>Gev, gev, gev, enim maxime nisi id, architecto vitae vel facere suscipit atque earum voluptate quasi assumenda pariatur iusto mollitia itaque, rerum, ratione alias.</p>
    <p>Some code:</p>
    <p><code>%%üîêŒ± 90/sDZGO0LNqRyA2XBYiv08DsToRdDHLJqw24yx5P0zWjrIfFAqqJU/CDaEFGblroE6Lo6Dr/+tFIgtGeRn42YSRvBTNWxESczTHDo9WX1XEzdA= üîê%%</code></p>
    <p>< !--%%üîêŒ± fLdwjDYy+lObc5OgqNq3dgcxG7MBjTX3BZFbnVZ4Y2VCcNQknpExvQA37dCiGNe4lJ4FkDTuaDINsRzmayRJEhsp/oz0/ZQ6 üîê%%-- ></p>
    <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Modi aspernatur qui facere blanditiis nostrum numquam quaerat magni eveniet, libero aliquam? Quia inventore eveniet quo laboriosam, natus provident laudantium animi quaerat.
        Eligendi ab eveniet ullam nulla alias accusamus tempora assumenda commodi ex, qui provident officia? Maxime eligendi provident minus? Repellendus eligendi dolore labore eos in cupiditate repudiandae, libero nemo illum ab.
        Quod laborum rem provident vero quaerat error repellat molestiae quibusdam et! Cumque architecto molestias ipsam voluptas aut dicta laborum aperiam eaque consectetur sed quam enim dignissimos, harum omnis magnam ratione.
        Sapiente ratione iusto quidem modi explicabo eius quibusdam, fugiat mollitia, repellendus nisi unde fuga, maiores exercitationem. Minima, rerum nesciunt. Nulla eius nemo officiis laudantium, odit vitae quis autem cupiditate consequuntur.
        Ratione, tempore dolore! Incidunt consequuntur asperiores repellat quos, dolorum quas, maiores, officia facere minus eveniet labore saepe deserunt possimus suscipit? Assumenda blanditiis magnam quasi nostrum suscipit debitis similique veritatis earum.
        Culpa beatae accusamus minus at pariatur laborum, aliquam nam natus deserunt, modi, eum facere! Tenetur odio pariatur accusantium repudiandae explicabo quae animi? Rerum blanditiis praesentium voluptate, illum culpa perspiciatis sequi.
    </p>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Id magnam magni earum nesciunt, impedit, vel minus ex culpa libero illo, quo odio perferendis aspernatur provident. Eum iste esse aliquid repellat?
        Dolores animi earum incidunt nesciunt magnam modi provident, quo perspiciatis quia suscipit error in similique, cum voluptatem obcaecati. Ab quibusdam minus vel expedita pariatur aliquid sed cumque porro excepturi temporibus.
        Soluta, incidunt. Quo assumenda eaque pariatur fugiat eos laborum fugit totam beatae laudantium sint provident consequatur maxime itaque sunt, harum tempora! Reprehenderit pariatur debitis quaerat facere. Architecto fugiat alias nam?
    </p>
    <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illo explicabo eos quod porro temporibus officia! Soluta, alias. Ipsam nihil pariatur, odit dolorum molestiae sunt neque corporis qui quis obcaecati veritatis?
        Et vero adipisci nihil architecto, vel placeat ea unde soluta numquam exercitationem, perferendis explicabo, quibusdam ipsam labore fugiat quaerat saepe ad. Inventore iusto veniam praesentium exercitationem magnam hic, pariatur possimus!
        Dignissimos laudantium assumenda impedit possimus optio asperiores maxime, nesciunt quibusdam, repellat dolorem voluptatibus voluptatem modi explicabo doloribus fugit sint magni. Exercitationem, nisi voluptatibus? Facilis dolore esse saepe veniam totam porro!
    </p>
    <p>
        <img src="https://images.unsplash.com/photo-1533228876829-65c94e7b5025?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" alt="" class="img-fluid">
    </p>
    <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Modi aspernatur qui facere blanditiis nostrum numquam quaerat magni eveniet, libero aliquam? Quia inventore eveniet quo laboriosam, natus provident laudantium animi quaerat.
        Eligendi ab eveniet ullam nulla alias accusamus tempora assumenda commodi ex, qui provident officia? Maxime eligendi provident minus? Repellendus eligendi dolore labore eos in cupiditate repudiandae, libero nemo illum ab.
        Quod laborum rem provident vero quaerat error repellat molestiae quibusdam et! Cumque architecto molestias ipsam voluptas aut dicta laborum aperiam eaque consectetur sed quam enim dignissimos, harum omnis magnam ratione.
        Sapiente ratione iusto quidem modi explicabo eius quibusdam, fugiat mollitia, repellendus nisi unde fuga, maiores exercitationem. Minima, rerum nesciunt. Nulla eius nemo officiis laudantium, odit vitae quis autem cupiditate consequuntur.
        Ratione, tempore dolore! Incidunt consequuntur asperiores repellat quos, dolorum quas, maiores, officia facere minus eveniet labore saepe deserunt possimus suscipit? Assumenda blanditiis magnam quasi nostrum suscipit debitis similique veritatis earum.
        Culpa beatae accusamus minus at pariatur laborum, aliquam nam natus deserunt, modi, eum facere! Tenetur odio pariatur accusantium repudiandae explicabo quae animi? Rerum blanditiis praesentium voluptate, illum culpa perspiciatis sequi.
    </p>
'''

field_2 = '''
    <h3>Side Notes</h3>
    <hr />
    <p>type: blog
    issue_time: 1970-01-01T00:00</p>
    <hr />
'''